-- DROP DATABASE if EXISTS alex;
-- CREATE DATABASE alex;

-- \c alex;

DROP TABLE IF EXISTS reviews;
-- DROP TABLE IF EXISTS products;
-- DROP TABLE IF EXISTS metaData;
DROP TABLE IF EXISTS characteristic_review;
DROP TABLE IF EXISTS characteristics;
-- DROP TABLE IF EXISTS photos;

-- CREATE TABLE products (
--   id integer GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
--   name VARCHAR(50),
--   slogan VARCHAR(2000),
--   description VARCHAR(1000),
--   category VARCHAR(40),
--   default_price INT
-- );

-- CREATE TABLE metaData (
--   id SERIAL PRIMARY KEY,
--   -- ratings ???,
--   -- recommended ???,
--   characteristics_id INT REFERENCES characteristics(id),
--   product_id INT REFERENCES products(id),
-- );

-- CREATE TABLE photos (
--   id SERIAL PRIMARY KEY,
--   url VARCHAR(100),
--   review_id INT REFERENCES reviews(id),
-- );

CREATE TABLE reviews (
  review_id integer GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  product_id INT NOT NULL,
  rating INT NOT NULL,
  date bigint NOT NULL,
  summary VARCHAR(2000) NOT NULL,
  body VARCHAR(1000) NOT NULL,
  recommended BOOLEAN NOT NULL DEFAULT false,
  reported BOOLEAN NOT NULL DEFAULT false,
  reviewer_name VARCHAR(200) NOT NULL,
  reviewer_email VARCHAR(400) NOT NULL,
  response VARCHAR(1000) DEFAULT null,
  helpfulness INT NOT NULL DEFAULT 0
  -- PRIMARY KEY (id),
  --   CONSTRAINT fk_products
  --     FOREIGN KEY (product_id)
  --      REFERENCES products(id)
);

CREATE TABLE characteristic_review (
  cr_id integer GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  characteristic_id INT,
  review_id INT NOT NULL,
  value INT NOT NULL
);

CREATE TABLE characteristics (
  characteristic_id integer GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  product_id INT NOT NULL,
  name VARCHAR(50) NOT NULL
);

-- COPY products (id, name, slogan, description, category, default_price)
-- FROM '/Users/alexnorvani/SDC/product.csv'
-- DELIMITER ','
-- CSV HEADER;

COPY reviews (review_id, product_id, rating, date, summary, body, recommended, reported, reviewer_name, reviewer_email, response, helpfulness)
FROM '/Users/alexnorvani/SDC/reviews.csv'
DELIMITER ','
CSV HEADER;

COPY characteristic_review (id, characteristic_id, review_id, value)
FROM '/Users/alexnorvani/SDC/characteristic_reviews.csv'
DELIMITER ','
CSV HEADER;

COPY characteristics (characteristic_id, product_id, name)
FROM '/Users/alexnorvani/SDC/characteristics.csv'
DELIMITER ','
CSV HEADER;